# Generated by Django 5.0 on 2023-12-23 18:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarkers', '0002_stroke'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LungCancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=255, null=True, verbose_name='Sex')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(110)], verbose_name='Age')),
                ('smoker', models.BooleanField(blank=True, null=True, verbose_name='Smoker')),
                ('yellow_fingers', models.BooleanField(blank=True, null=True, verbose_name='Yellow fingers')),
                ('anxiety', models.BooleanField(blank=True, null=True, verbose_name='Anxiety')),
                ('peer_pressure', models.BooleanField(blank=True, null=True, verbose_name='Peer pressure')),
                ('chronic_disease', models.BooleanField(blank=True, null=True, verbose_name='Chronic disease')),
                ('fatigue', models.BooleanField(blank=True, null=True, verbose_name='Fatigue')),
                ('allergy', models.BooleanField(blank=True, null=True, verbose_name='Allergy')),
                ('wheezing', models.BooleanField(blank=True, null=True, verbose_name='Wheezing')),
                ('alcohol_consumption', models.BooleanField(blank=True, null=True, verbose_name='Alcohol Consumption')),
                ('coughing', models.BooleanField(blank=True, null=True, verbose_name='Coughing')),
                ('shortness_of_breath', models.BooleanField(blank=True, null=True, verbose_name='Shortness of breath')),
                ('hepatitis', models.BooleanField(blank=True, null=True, verbose_name='Hepatitis')),
                ('chronic_fatigue', models.BooleanField(blank=True, null=True, verbose_name='Chronic fatigue')),
                ('swallowing_difficulty', models.BooleanField(blank=True, null=True, verbose_name='Swallowing difficulty')),
                ('chest_pain', models.BooleanField(blank=True, null=True, verbose_name='Chest pain')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lung_cancer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
