# Generated by Django 5.0 on 2023-12-24 17:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarkers', '0004_lungcancer_result_malaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='malaria',
            name='image',
            field=models.ImageField(upload_to='diseases/malaria'),
        ),
        migrations.CreateModel(
            name='HeartFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(null=True, verbose_name='Result')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(110)], verbose_name='Age')),
                ('sex', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=255, null=True, verbose_name='Sex')),
                ('cp', models.IntegerField(blank=True, verbose_name='Chest pain type')),
                ('trestbps', models.IntegerField(blank=True, verbose_name=' Resting blood pressure')),
                ('chol', models.IntegerField(blank=True, verbose_name='Cholesterol')),
                ('fbs', models.IntegerField(blank=True, verbose_name=' Fasting blood sugar')),
                ('restecg', models.IntegerField(blank=True, verbose_name='Resting ECG')),
                ('thalach', models.IntegerField(blank=True, verbose_name='Max heart rate')),
                ('exang', models.BooleanField(blank=True, verbose_name='Exercise induced angina')),
                ('oldpeak', models.FloatField(blank=True, verbose_name='ST depression')),
                ('slope', models.IntegerField(blank=True, verbose_name=' Slope of peak exercise ST segment')),
                ('ca', models.IntegerField(blank=True, verbose_name='Number of major vessels colored by flourosopy')),
                ('thal', models.IntegerField(blank=True, verbose_name='Thalassemia')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hearth_failure', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
