# Generated by Django 5.0 on 2023-12-25 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarkers', '0006_cvd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvd',
            name='cholesterol_level',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cholesterol level'),
        ),
        migrations.CreateModel(
            name='HIV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(null=True, verbose_name='Result')),
                ('hiv_diagnosis', models.IntegerField(blank=True, null=True, verbose_name='HIV diagnoses')),
                ('hiv_diagnosis_rate', models.FloatField(blank=True, null=True, verbose_name='HIV diagnosis rate')),
                ('concurrent_diagnosis', models.IntegerField(blank=True, null=True, verbose_name='Concurrent diagnoses')),
                ('patients_treatment_3_months', models.IntegerField(blank=True, null=True, verbose_name='% linked to care within 3 months')),
                ('aids_diagnosis_rate', models.FloatField(blank=True, null=True, verbose_name='AIDS diagnosis rate')),
                ('plwdhi_prevalence', models.FloatField(blank=True, null=True, verbose_name='PLWDHI prevalence')),
                ('viral_suppression', models.IntegerField(blank=True, null=True, verbose_name='% viral suppression')),
                ('deaths', models.IntegerField(blank=True, null=True, verbose_name='Deaths')),
                ('death_rate', models.FloatField(blank=True, null=True, verbose_name='Death rate')),
                ('hiv_death_rate', models.FloatField(blank=True, null=True, verbose_name='HIV-related death rate')),
                ('non_hiv_death_rate', models.FloatField(blank=True, null=True, verbose_name='Non-HIV-related death rate')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hiv', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
