# Generated by Django 5.0 on 2023-12-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarkers', '0008_copd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copd',
            name='gender',
            field=models.IntegerField(choices=[(0, 'FEMALE'), (1, 'MALE')]),
        ),
    ]
