# Generated by Django 5.0 on 2023-12-26 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarkers', '0009_alter_copd_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='copd',
            name='gender',
            field=models.IntegerField(blank=True, null=True, verbose_name='gender'),
        ),
        migrations.CreateModel(
            name='Leukemia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(null=True, verbose_name='Result')),
                ('image', models.ImageField(upload_to='diseases/leukemia')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Leukemia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Melanoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(null=True, verbose_name='Result')),
                ('image', models.ImageField(upload_to='diseases/malanoma')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='melanoma', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pneumonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(null=True, verbose_name='Result')),
                ('image', models.ImageField(upload_to='diseases/pneumonia')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pneumonia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
